# Generated by Django 4.2.1 on 2023-05-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('age', models.CharField(default='age', max_length=100)),
                ('phone', models.CharField(default='phone', max_length=100)),
                ('adress', models.CharField(default='adress', max_length=100)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('activ', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, choices=[('id', 'id'), ('name', 'name')], max_length=100, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
