# Generated by Django 4.2.1 on 2023-05-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finger',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
